name: Build and Release VSCode REH Linux ARM64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ \
            libx11-dev libxkbfile-dev libsecret-1-dev \
            libkrb5-dev python-is-python3

      - name: Setup Node.js 22.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build VSCode (reh-linux-arm64-min)
        run: node node_modules/gulp/bin/gulp.js compile-build

      - name: Move build folder into workspace
        run: |
          mkdir -p build-output
          cp -r ../vscode-reh-linux-arm64 build-output/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-reh-linux-arm64
          path: .

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-reh-linux-arm64
          path: vscode-reh-linux-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: vscode-reh-linux-arm64/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
