name: Build and Release VSCode REH Linux ARM64

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'          # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ \
            libx11-dev libxkbfile-dev libsecret-1-dev \
            libkrb5-dev python-is-python3

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 4. Install Node dependencies
      - name: Install npm dependencies
        run: npm ci

      # 5. Build VSCode for Linux ARM64
      - name: Build VSCode (reh-linux-arm64-min)
        run: node node_modules/gulp/bin/gulp.js vscode-reh-linux-arm64-min

      # 6. Upload artifact for debugging (optional)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-reh-linux-arm64
          path: ../vscode-reh-linux-arm64

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-reh-linux-arm64
          path: vscode-reh-linux-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: vscode-reh-linux-arm64/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
